name: shelf_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_jsonwebtoken: ^2.4.0
  hive: ^2.0.5
  postgres: ^2.4.3
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  http: ^0.13.4
  lints: ^1.0.1
  test: ^1.20.0
  test_process: ^2.0.2
